name: Build and Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build and publish on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2022, windows-11-arm, macos-15]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install xmake
        if: runner.os != 'Linux'
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - name: Ensure Commands
        if: runner.os != 'Windows'
        run: |
          sudo ln -sf $(which python3) /usr/local/bin/python

      - name: Build Wheels
        run: python -m cibuildwheel --archs auto64 --output-dir wheelhouse
        env:
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: bstream-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl


  publish:
    name: Publish Wheels to PyPI
    runs-on: ubuntu-latest
    needs: 
      - build_wheels

    steps:
      - name: Restore Artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: bstream-wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}